FROM --platform=linux/arm64 public.ecr.aws/docker/library/python:3.12-slim

WORKDIR /app

RUN pip install --upgrade pip

# Install system dependencies for PyAudio and other packages

# Copy requirements and install remaining dependencies
COPY requirements.txt ./
COPY strands_agents-1.20.1.dev5+g9c3223db2-py3-none-any.whl ./
RUN pip install -r requirements.txt
RUN pip install strands_agents-1.20.1.dev5+g9c3223db2-py3-none-any.whl[bidi]

# Copy agent file
COPY server.py ./
COPY elevenlabs_io.py ./

# Set environment variables
ENV HOST="0.0.0.0"
ENV PORT=8080

# Expose port
EXPOSE 8080

# Run application directly
CMD ["python", "server.py"]
